version: '3.1'

services:

  opentheso2-db:
    build: 
      context: .
      dockerfile: ./Dockerfile-postgres
    image: miledrousset/opentheso2-postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: opentheso
      POSTGRES_PASSWORD: opentheso
      PGDATA: /pgdata
    volumes:
      - /docker-entrypoint-initdb.d/opentheso2-pgdata

  opentheso:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        OPENTHESO_VERSION: "23.09.01"
    image: miledrousset/opentheso2
    restart: always
    depends_on:
      - opentheso2-db
    ports:
      - 80:8080

volumes:
  opentheso-pgdata:
    external: false